build: specify GLib version
Otherwise features getting deprecated from glib break the build:

  nm-ssh-service.c: In function ‘nm_ssh_plugin_class_init’:
  nm-ssh-service.c:1479:2: error: ‘g_type_class_add_private’ is deprecated
      [-Werror=deprecated-declarations]

2.26 was chosen pretty arbitrarily -- we do build just fine with that
version and it's the first one that seems to define a version macro.